name: Triggering Workflow 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run CI steps for Workflow 1
        run: echo "Running CI steps for Workflow 1"
