name: Triggering Workflow 1

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cancel ongoing dependent workflows
        uses: actions/github-script@v6
        with:
          script: |
            const runs = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'dependent-workflow.yml',
              status: 'in_progress'
            });
            for (const run of runs.data.workflow_runs) {
              await github.rest.actions.cancelWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id
              });
            }
      - name: Run CI steps for Workflow 1
        run: echo "Running CI steps for Workflow 1"
      - name: Create status file
        run: echo "workflow1=completed" >> status1.txt
      - name: Cache status file
        uses: actions/cache@v3
        with:
          path: status1.txt
          key: ${{ runner.os }}-workflow1-status
